#!/bin/bash
cp -r ~/temporal/src/parmap/* parmap
sed -r 's/develop = True/develop = False/' parmap/tests
find parmap/tests/ -type f -exec sed -i -e 's/develop = True/develop = False/' {} \;

cd parmap
nosetests
